### ISSUE TITLE
Maximum recursion depth exceeded - Traefik

### ISSUE THREAD

**Issue by joelanguera** [ahembree/ansible-hms-docker#99]
OS: Ubuntu 24.04 LTS
Ansible: core 2.17.1
Docker: 27.0.2

Updating from version 0.0 to 1.4, I got an `maximum recursion depth exceeded` exception error in the `hmsdocker : Ensure docker-compose.yml file.` task.

I pulled the latest changes, migrated vars, updated vars using make update and ran the playbook and this error arised. Seems like there is an issue with something related to traefik. Noticed there was a var change there but I don't even have traefik enabled.

Pasting the full log:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: recursive loop detected in template string: {{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}. maximum recursion depth exceeded
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while templating '{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: recursive loop detected in template string: {{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}. maximum recursion depth exceeded"}
```

**Comment by joelanguera** [comment]
Fixed it commenting the `hmsdocker_traefik_static_config_location` variable inside `traefik.yml`.

Ran `make update` a couple of times but always got the same output:
```shell
sudo make update
Updating from Git repo...
Already up to date.
Updating variable names
Updating Traefik variables
Update finished

``` 

Then checked `traefik.yml` variables, where said: "To fix: run `make update`", but running that again didn't do anything. Commenting that deprecated variable made the playbook run smoothly.
```
# Where static config files are stored for Traefik (middlewares and external hosts)
# Deprecation notice:
# the `hmsdocker_traefik_static_config_location` variable was removed on 5/31/2024 but will still work for the time being.
# It will be removed at least 1 year from the deprecation date (6/1/2025) and then will be fully removed and no longer work
# To fix: run `make update`
hmsdocker_traefik_static_config_location: "{{ hmsdocker_traefik_static_config_location | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}"

```

**Comment by ahembree** [comment]
Thanks for the report!

At a quick glance, it looks like I may have messed up the command used to replace `traefik_ext_hosts_configs_path` (the deprecated variable) with `hmsdocker_traefik_static_config_location` for existing installs as that last line _should_ have actually been:

```yaml
hmsdocker_traefik_static_config_location: "{{ traefik_ext_hosts_configs_path | default(hms_docker_apps_path + '/traefik/config/static_confs/') }}"
```

I've pushed a fix for this in another branch (https://github.com/ahembree/ansible-hms-docker/commit/cd947ecf9e4aab647b45e1a1e8d835a49254c49d) that I hope to merge soon.

Just to confirm, this was an existing install and Traefik was completely disabled?

**Comment by joelanguera** [comment]
Yes, that was an existing instal from what I'd say was v0.0. And yeah, traefik was completely disabled (I had the container disabled but don't remember if I switched off anything else manually) I can share the config files though.

**Comment by ahembree** [comment]
Sweet thanks for the info. I think this issue occurred during the variable "compilation" process of Ansible, so even with Traefik fully disabled this would still happen. The fix will be merged in shortly along with some other massive changes.
